# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: rahulnikam
# "service" is the name of this project. This will also be added to your AWS resource names.
service: dummy-api-int-v1

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 2048
  timeout: 15 
  stage: dev
  region: ap-south-1

functions:
  hello:
    handler: handler.startup
    events:
      - http: ANY /{proxy+}
      - http: ANY /
      